### ISSUE TITLE
Mobile view is not responsive

### ISSUE THREAD

**Issue by RaviprasathKJ** [bitspaceorg/url-shortner#14]
![WhatsApp Image 2023-05-09 at 10 54 29](https://user-images.githubusercontent.com/118717432/237001731-fc8753df-9996-461d-81d1-0edbe4ee6586.jpg)

**Comment by RaviprasathKJ** [comment]
please assign to me  @RahulNavneeth

**Comment by RahulNavneeth** [comment]
Sure 👍
