### ISSUE TITLE
Web Page Title Irresponsive

### ISSUE THREAD

**Issue by Sak1012** [bitspaceorg/url-shortner#15]
The web page title is not getting updated
<img width="1407" alt="Screenshot 2023-05-09 at 11 37 14 AM" src="https://user-images.githubusercontent.com/75414859/237008509-47a412c7-aff8-4b30-9fbc-c1059a50c412.png">

## How to reproduce the error:
Open the website and take a look at the title

**Comment by Sak1012** [comment]
Can I work on this issue @bitspaceorg/board

**Comment by RahulNavneeth** [comment]
Sure 👍
