### ISSUE TITLE
Shorten Button not aligned

### ISSUE THREAD

**Issue by Ren-Gen22** [bitspaceorg/url-shortner#16]
The shorten button is not aligned. it about few pixels down, 
![image](https://user-images.githubusercontent.com/110223586/237009397-e177b780-f856-4b79-9b2b-51da09ce052b.png)
*Fixing it by aligning it a lil bit top

**Comment by Ren-Gen22** [comment]
Check it out:
The button is misaligned at 100% and 110% zoom and gets realigned when zoomed in or out

https://github.com/bitspaceorg/url-shortner/assets/110223586/26c4d792-93e8-4e16-8d85-82cf425ebbe3

Responsiveness of the webpage is broken...

**Comment by RaviprasathKJ** [comment]
The issue #16 was resolved recently in pr  #21.
PLAT and close the issue if you guys are okay with it @RahulNavneeth @Ren-Gen22 .
